-- ============================================================
-- BeSQL Platform — CREATE TABLE statements
-- For quoted CamelCase tables used by BSQ-009 to BSQ-100 datasets
-- ============================================================

BEGIN;

CREATE TABLE IF NOT EXISTS "CitizenMentalHealth" (
  "CITIZEN_ID"        INT PRIMARY KEY,
  "CITIZEN_NAME"      VARCHAR(100) NOT NULL,
  "SECTOR"            VARCHAR(100) NOT NULL,
  "STABILITY_RATING"  NUMERIC(5,2) NOT NULL,
  "LAST_CHECKUP"      DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS "OperativeProfiles" (
  "OPERATIVE_ID"          INT PRIMARY KEY,
  "OPERATIVE_NAME"        VARCHAR(100) NOT NULL,
  "CLEARANCE_LEVEL"       VARCHAR(50) NOT NULL,
  "ORGANIZATIONS_COUNT"   INT NOT NULL,
  "RECRUITMENT_DATE"      DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS "AgentRecords" (
  "RECORD_ID"         INT PRIMARY KEY,
  "AGENT_NAME"        VARCHAR(100) NOT NULL,
  "DIVISION_NAME"     VARCHAR(100) NOT NULL,
  "ENTRY_DATE"        DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS "CreditLedger" (
  "TXN_ID"            INT PRIMARY KEY,
  "ACCOUNT_ID"        INT NOT NULL,
  "CREDITS"           INT NOT NULL,
  "TXN_DATE"          DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS "Agents" (
  "AGENT_ID"          INT PRIMARY KEY,
  "AGENT_NAME"        VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS "Exchanges" (
  "YEAR"              INT NOT NULL,
  "GIVER_ID"          INT NOT NULL,
  "RECEIVER_ID"       INT NOT NULL,
  PRIMARY KEY ("YEAR","GIVER_ID","RECEIVER_ID")
);

CREATE TABLE IF NOT EXISTS "Follows" (
  "CITIZEN_ID"            INT NOT NULL,
  "FOLLOWED_CITIZEN_ID"   INT NOT NULL,
  PRIMARY KEY ("CITIZEN_ID","FOLLOWED_CITIZEN_ID")
);

CREATE TABLE IF NOT EXISTS "Posts" (
  "POST_ID"           INT PRIMARY KEY,
  "CITIZEN_ID"        INT NOT NULL,
  "CONTENT"           TEXT NOT NULL,
  "POST_DATE"         DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS "Divisions" (
  "DIVISION_ID"       INT PRIMARY KEY,
  "DIVISION_NAME"     VARCHAR(100) NOT NULL,
  "CHIEF_ID"          INT
);

CREATE TABLE IF NOT EXISTS "DivisionAgents" (
  "AGENT_ID"          INT PRIMARY KEY,
  "AGENT_NAME"        VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS "OperativeStatus" (
  "OPERATIVE_ID"        INT PRIMARY KEY,
  "OPERATIVE_NAME"      VARCHAR(100) NOT NULL,
  "DIVISION"            VARCHAR(100) NOT NULL,
  "ENERGY_LEVEL"        INT NOT NULL,
  "LAST_MISSION_DATE"   DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS "CreditTransactions" (
  "TRANSACTION_ID"    INT PRIMARY KEY,
  "SENDER_NAME"       VARCHAR(100) NOT NULL,
  "RECEIVER_NAME"     VARCHAR(100) NOT NULL,
  "BASE_VALUE"        INT NOT NULL,
  "MULTIPLIER"        INT NOT NULL
);

CREATE TABLE IF NOT EXISTS "SectorStats" (
  "SECTOR_ID"         INT PRIMARY KEY,
  "SECTOR"            VARCHAR(100) NOT NULL,
  "POPULATION"        INT NOT NULL,
  "THREAT_LEVEL"      VARCHAR(50) NOT NULL,
  "COMMANDER"         VARCHAR(100) NOT NULL,
  "ESTABLISHED"       INT NOT NULL
);

CREATE TABLE IF NOT EXISTS "MissionLogs" (
  "MISSION_ID"        INT PRIMARY KEY,
  "AGENT_NAME"        VARCHAR(100) NOT NULL,
  "MISSION_TYPE"      VARCHAR(50) NOT NULL,
  "SUCCESS"           SMALLINT NOT NULL,
  "DURATION_HRS"      INT NOT NULL,
  "MISSION_DATE"      DATE NOT NULL,
  "SECTOR"            VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS "AgentSkills" (
  "AGENT_ID"          INT NOT NULL,
  "AGENT_NAME"        VARCHAR(100) NOT NULL,
  "SKILL"             VARCHAR(100) NOT NULL,
  "PROFICIENCY"       INT NOT NULL,
  "CERTIFIED"         SMALLINT NOT NULL,
  PRIMARY KEY ("AGENT_ID","SKILL")
);

CREATE TABLE IF NOT EXISTS "DataVaultInventory" (
  "ITEM_ID"           INT PRIMARY KEY,
  "ITEM_NAME"         VARCHAR(150) NOT NULL,
  "CATEGORY"          VARCHAR(100) NOT NULL,
  "QUANTITY"          INT NOT NULL,
  "UNIT_COST"         INT NOT NULL,
  "LAST_RESTOCKED"    DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS "AgentRankHistory" (
  "HISTORY_ID"        INT PRIMARY KEY,
  "AGENT_NAME"        VARCHAR(100) NOT NULL,
  "RANK"              VARCHAR(100) NOT NULL,
  "FROM_DATE"         DATE NOT NULL,
  "TO_DATE"           DATE
);

CREATE TABLE IF NOT EXISTS "ThreatAlerts" (
  "ALERT_ID"          INT PRIMARY KEY,
  "SECTOR"            VARCHAR(100) NOT NULL,
  "THREAT_TYPE"       VARCHAR(100) NOT NULL,
  "SEVERITY"          VARCHAR(50) NOT NULL,
  "REPORTED_AT"       TIMESTAMP NOT NULL,
  "RESOLVED"          SMALLINT NOT NULL
);

CREATE TABLE IF NOT EXISTS "CitizenRegistry" (
  "CITIZEN_ID"         INT PRIMARY KEY,
  "CITIZEN_NAME"       VARCHAR(100) NOT NULL,
  "SECTOR"             VARCHAR(100) NOT NULL,
  "REGISTRATION_DATE"  DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS "SectorStatus" (
  "SECTOR_ID"          INT PRIMARY KEY,
  "SECTOR_NAME"        VARCHAR(100) NOT NULL,
  "STABILITY_INDEX"    INT NOT NULL,
  "POPULATION"         INT NOT NULL,
  "LAST_SCAN_DATE"     DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS "AnomalyTracker" (
  "ANOMALY_ID"         INT PRIMARY KEY,
  "ANOMALY_NAME"       VARCHAR(150) NOT NULL,
  "SECTOR"             VARCHAR(100) NOT NULL,
  "SEVERITY_SCORE"     INT NOT NULL,
  "DETECTED_DATE"      DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS "BriefingLog" (
  "LOG_ID"             INT PRIMARY KEY,
  "AGENT_NAME"         VARCHAR(100) NOT NULL,
  "TEAM_SIZE"          INT NOT NULL,
  "BRIEFING_DATE"      DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS "ArchiveAccess" (
  "AGENT_ID"           INT NOT NULL,
  "AGENT_NAME"         VARCHAR(100) NOT NULL,
  "ARCHIVE_ID"         INT NOT NULL,
  "ARCHIVE_NAME"       VARCHAR(150) NOT NULL,
  PRIMARY KEY ("AGENT_ID","ARCHIVE_ID")
);

CREATE TABLE IF NOT EXISTS "Sectors" (
  "SECTOR_ID"          INT PRIMARY KEY,
  "SECTOR_NAME"        VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS "Assignments" (
  "AGENT_ID"           INT NOT NULL,
  "SECTOR_ID"          INT NOT NULL,
  PRIMARY KEY ("AGENT_ID","SECTOR_ID")
);

CREATE TABLE IF NOT EXISTS "CafeOrders" (
  "ORDER_ID"           INT PRIMARY KEY,
  "CITIZEN_ID"         INT NOT NULL,
  "DRINK"              VARCHAR(120) NOT NULL,
  "ORDER_TIME"         TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS "TrainingScores" (
  "SESSION_ID"         INT PRIMARY KEY,
  "AGENT_NAME"         VARCHAR(100) NOT NULL,
  "SESSION_DATE"       DATE NOT NULL,
  "POINTS"             INT NOT NULL
);

CREATE TABLE IF NOT EXISTS "YearlyCredits" (
  "YEAR"               INT PRIMARY KEY,
  "TOTAL_CREDITS"      INT NOT NULL
);

COMMIT;

